openapi: 3.0.0
info:
  title: Calculator API
  version: 1.0.0
  description: API pour utiliser la calculatrice sans interface graphique
servers:
  - url: http://localhost:3000
paths:
  /api/calculator/add:
    post:
      summary: Additionne deux nombres
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  example: 5
                b:
                  type: number
                  example: 3
      responses:
        '200':
          description: Résultat de l'addition
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 8
        '400':
          description: Erreur dans les paramètres
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "All arguments must be numbers."
  /api/calculator/subtract:
    post:
      summary: Soustrait deux nombres
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  example: 5
                b:
                  type: number
                  example: 3
      responses:
        '200':
          description: Résultat de la soustraction
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 2
        '400':
          description: Erreur dans les paramètres
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "All arguments must be numbers."
  /api/calculator/multiply:
    post:
      summary: Multiplie deux nombres
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  example: 5
                b:
                  type: number
                  example: 3
      responses:
        '200':
          description: Résultat de la multiplication
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 15
        '400':
          description: Erreur dans les paramètres
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "All arguments must be numbers."
  /api/calculator/divide:
    post:
      summary: Divise deux nombres
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                a:
                  type: number
                  example: 6
                b:
                  type: number
                  example: 3
      responses:
        '200':
          description: Résultat de la division
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: number
                    example: 2
        '400':
          description: Erreur dans les paramètres ou division par zéro
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    examples:
                      invalidParams: "All arguments must be numbers."
                      divisionByZero: "Division by zero is not allowed."